# Generated by Django 5.1.4 on 2025-08-06 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
