# Generated by Django 5.1.4 on 2025-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_task_model_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='user_id',
        ),
        migrations.AddField(
            model_name='task_model',
            name='user_name',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
