# Generated by Django 5.1.4 on 2025-08-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_task_model_user_id_task_model_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='user_name',
            field=models.CharField(max_length=40),
        ),
    ]
